### ISSUE TITLE
HBase RegionServer down due to permission denied

### ISSUE THREAD

**Issue by takabow** [takabow/cloudera-demo-env#19]
```
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=hbase, access=EXECUTE, inode="/tmp":hdfs:supergroup:d-wx------
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:279)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:260)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkTraverse(DefaultAuthorizationProvider.java:201)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:154)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:152)
```

**Comment by takabow** [comment]
It seems that HDFS canary test creates /tmp with wrong permission if /tmp doesn't exist.

**Comment by takabow** [comment]
A simple workaround is disabling `hdfs_canary_health_enabled`
